task: qa
seed: 3407
wandb_path: v2-inference-testing-cuda-domain-discriminator
fewshot_qa: False
inference_device: cuda
train: True
inference: True
save_model_optimizer: True
load_model_optimizer: False
load_path: v2-inference-testing-cuda
use_drqa: True
create_drqa_tfidf: False
drqa_top_k: 5
domain_discriminator: True

data:
  train_data_path: data-dir/train/df_train.pkl
  val_data_path: data-dir/val/df_val.pkl
  test_data_path: data-dir/test/df_test.pkl
  train_batch_size: 32
  val_batch_size: 32
  apply_aliasing: False
  pad_on_right: True
  max_length: 512
  doc_stride: 128
  tokenizer_batch_size: 32

training:
  epochs: 1
  optimizer: adam
  lr: 0.00002
  sched_function: none
  sched_func_params: {}
  sched_params:
    monitor: val_loss
  evaluate_every: 1
  model_epochs: 1
  discriminator_epochs: 3
  d_lr: 0.001

model:
  model_path: google/bert_uncased_L-2_H-128_A-2
  params: {}
  non_pooler: True
  dim: 128