output_dir: /content/drive/context_pretrained_electra-small-finetuned-squadv2
model_type: bert
model_name_or_path: mrm8488/electra-small-finetuned-squadv2
do_train: True
train_data_file: 'context_MLM.txt'
do_eval: False
eval_data_file: 'context_MLM.txt'
mlm: True
per_gpu_train_batch_size: 4
gradient_accumulation_steps: 4
num_train_epochs: 100
save_total_limit: 1
should_continue: False
mlm_probability: 0.15
config_name: null
tokenizer_name: null
cache_dir: null
block_size: 512 
evaluate_during_training: False
per_gpu_eval_batch_size: 4
learning_rate: 5e-5
weight_decay: 0.0
adam_epsilon: 1e-8
max_grad_norm: 1.0
max_steps: -1
warmup_steps: 0
logging_steps: 500
save_steps: 500
save_total_limit: null
eval_all_checkpoints: False
no_cuda: False
overwrite_output_dir: False
overwrite_cache: False
seed: 42
fp16: False
fp16_opt_level: '01'
local_rank: -1
server_ip: ''
server_port: ''
freeze_layers: 4
freeze: True
