# -*- coding: utf-8 -*-
"""context_aggregation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IxFs_44g8NmngVE5Du1NsYYkwRuDNuZn
"""

import numpy as np
import pandas as pd
import os

#Read data from paths
df = pd.read_pickle('df.pkl')

#df_final = pd.concat([df_1, df_2, df_3])

#if multiple datasets concat them

a = df['context']   # or df_final['context']

base_filename = 'context_MLM.txt'
with open(os.path.join(base_filename),'w') as outfile:
    a.to_string(outfile, index = False)
